name: Run Tests
'on':
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm install
        shell: bash
      - name: Run Jest Tests
        run: |
          npm test
        shell: bash
